image: node:14.15.3

pipelines:
  branches:

    # Staging
    master:

      - step:
          name: Staging
          deployment: staging
          services:
            - docker
          caches:
            - docker
          script:
            - export IMAGE=$DOCKER_ACCOUNT/$DOCKER_IMAGE:latest
            - printf "DEPLOY\n    env  $BITBUCKET_DEPLOYMENT_ENVIRONMENT\n    img  $IMAGE\n\nSERVER\n    host $SERVER_HOST\n    port $SERVER_PORT\n    user $SERVER_USER\n\nAPP\n	port $PORT\n    url  $API_URL\n";

            # Build the image
            - docker build --build-arg API_URL=$API_URL -t $IMAGE .
            - docker tag $IMAGE

            # Push the image
            - docker login --username $DOCKER_ACCOUNT --password $DOCKER_PASSWORD
            - docker push $IMAGE

            # Deploy on the server
            - export DEPLOY="deploy-$DOCKER_IMAGE-$BITBUCKET_DEPLOYMENT_ENVIRONMENT-$RANDOM.sh"
            - scp -o StrictHostKeyChecking=no deploy/deploy.sh $SERVER_USER@$SERVER_HOST@SERVER_PORT:$DEPLOY
            - ssh -o StrictHostKeyChecking=no                  $SERVER_USER@$SERVER_HOST@SERVER_PORT "./$DEPLOY && rm $DEPLOY"
                      DOCKER_ACCOUNT='${DOCKER_ACCOUNT}'
                      DOCKER_IMAGE='${DOCKER_IMAGE}'
                      PORT='${PORT}'
                  ./$DEPLOY &&
                  rm ./$DEPLOY"

    # Production
    production-stojic:

      - step:
          name: Staging
          deployment: staging
          services:
            - docker
          caches:
            - docker
          script:
            - export IMAGE=$DOCKER_ACCOUNT/$DOCKER_IMAGE:$BITBUCKET_COMMIT
            - printf "DEPLOY\n    env  $BITBUCKET_DEPLOYMENT_ENVIRONMENT\n    img  $IMAGE\n\nSERVER\n    host $SERVER_HOST\n    port $SERVER_PORT\n    user $SERVER_USER\n\nAPP\n	port $PORT\n    url  $API_URL\n";

            # Build the image
            - docker build --build-arg API_URL=$API_URL -t $IMAGE .
            - docker tag $IMAGE

            # Push the image
            - docker login --username $DOCKER_ACCOUNT --password $DOCKER_PASSWORD
            - docker push $IMAGE

            # Deploy on the server
            - export DEPLOY="deploy-$DOCKER_IMAGE-$BITBUCKET_DEPLOYMENT_ENVIRONMENT-$RANDOM.sh"
            - scp -o StrictHostKeyChecking=no deploy/deploy.sh $SERVER_USER@$SERVER_HOST@SERVER_PORT:$DEPLOY
            - ssh -o StrictHostKeyChecking=no                  $SERVER_USER@$SERVER_HOST@SERVER_PORT "./$DEPLOY && rm $DEPLOY"

definitions:
  services:
    docker:
      memory: 3072
